### ISSUE TITLE
Python/Fission expected data format is incompatible with other implementations

### ISSUE THREAD

**Issue by juliogomez** [fonk-apps/fonk-examples#14]
Guestbook running on python/fission seem to expect entries in a different format when reading with the 'list' function, compared to for example nodejs on openfaas/kubeless/openwhisk. These 3 last ones can read from (and write to) the same database without any issues, while fission cannot read from an existing list of entries created with any of the nodejs examples.

Let's see an example, where we start with an empty list.

```
❯ wsk action invoke list -i --result
{
    "entries": []
}
```

Then we add our first entry with the openwhisk function.

```
❯ wsk action invoke create --param text 'Hello from openwhisk' -i --result
{
    "_id": "5bcb9868377aa00005dade97",
    "text": "Hello from openwhisk",
    "updatedAt": 1540069480195
}
```

We check it can be read with openwhisk and kubeless, but not with fission.

```
~/dev/fonk/fonk-examples/guestbook/faas/fission/python master*
❯ wsk action invoke list -i --result
{
    "entries": [
        {
            "_id": "5bcb9868377aa00005dade97",
            "text": "Hello from openwhisk",
            "updatedAt": 1540069480195
        }
    ]
}

~/dev/fonk/fonk-examples/guestbook/faas/fission/python master*
❯ kubeless function call list
{"entries":[{"_id":"5bcb9868377aa00005dade97","text":"Hello from openwhisk","updatedAt":1540069480195}]}

~/dev/fonk/fonk-examples/guestbook/faas/fission/python master*
❯ fission function test --name list
Error calling function list: 500 {'error': "ObjectId('5bcb9868377aa00005dade97') is not JSON serializable"}[2018-10-19 06:47:06.264921368 +0000 UTC] 2018/10/19 06:47:06 fetcher received fetch request and started downloading: {1 {list-pkg-zip-pidd  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] }   9564e01b-d313-11e8-b06e-005056a3aefa [] []}
[2018-10-19 06:47:08.368629978 +0000 UTC] 2018/10/19 06:47:08 Successfully placed at /userfunc/9564e01b-d313-11e8-b06e-005056a3aefa
[2018-10-19 06:47:08.368650992 +0000 UTC] 2018/10/19 06:47:08 Checking secrets/cfgmaps
[2018-10-19 06:47:08.368655239 +0000 UTC] 2018/10/19 06:47:08 Completed fetch request
[2018-10-19 06:47:08.368658566 +0000 UTC] 2018/10/19 06:47:08 elapsed time in fetch request = 2.148858421s
[2018-10-19 06:57:54.80290473 +0000 UTC] 2018/10/19 06:57:54 Received SIGTERM : Dumping stack trace
[2018-10-19 06:57:54.802943884 +0000 UTC] goroutine 21 [running]:
[2018-10-19 06:57:54.802949116 +0000 UTC] runtime/debug.Stack(0x1a60b00, 0xc420056790, 0x5041ec)
[2018-10-19 06:57:54.802953029 +0000 UTC] 	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
[2018-10-19 06:57:54.802957098 +0000 UTC] runtime/debug.PrintStack()
[2018-10-19 06:57:54.803003866 +0000 UTC] 	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:16 +0x22
[2018-10-19 06:57:54.8030081 +0000 UTC] main.dumpStackTrace()
[2018-10-19 06:57:54.803011948 +0000 UTC] 	src/github.com/fission/fission/environments/fetcher/cmd/main.go:24 +0x20
[2018-10-19 06:57:54.803015786 +0000 UTC] main.main.func1(0xc4200ab860)
[2018-10-19 06:57:54.803019526 +0000 UTC] 	src/github.com/fission/fission/environments/fetcher/cmd/main.go:35 +0x7d
[2018-10-19 06:57:54.803023439 +0000 UTC] created by main.main
[2018-10-19 06:57:54.803026967 +0000 UTC] 	src/github.com/fission/fission/environments/fetcher/cmd/main.go:32 +0xcb
[2018-10-19 07:10:05.382597184 +0000 UTC] 2018/10/19 07:10:05 fetcher received fetch request and started downloading: {1 {list-pkg-zip-pidd  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] }   9564e01b-d313-11e8-b06e-005056a3aefa [] []}
[2018-10-19 07:10:07.867294867 +0000 UTC] 2018/10/19 07:10:07 Successfully placed at /userfunc/9564e01b-d313-11e8-b06e-005056a3aefa
[2018-10-19 07:10:07.867687488 +0000 UTC] 2018/10/19 07:10:07 Checking secrets/cfgmaps
[2018-10-19 07:10:07.867700733 +0000 UTC] 2018/10/19 07:10:07 Completed fetch request
[2018-10-19 07:10:07.867704898 +0000 UTC] 2018/10/19 07:10:07 elapsed time in fetch request = 2.485619924s
[2018-10-19 07:19:54.968316309 +0000 UTC] 2018/10/19 07:19:54 Received SIGTERM : Dumping stack trace
[2018-10-19 07:19:54.96848127 +0000 UTC] goroutine 6 [running]:
[2018-10-19 07:19:54.968494782 +0000 UTC] runtime/debug.Stack(0x1a60b00, 0xc42005a790, 0x5041ec)
[2018-10-19 07:19:54.968502279 +0000 UTC] 	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
[2018-10-19 07:19:54.968509496 +0000 UTC] runtime/debug.PrintStack()
[2018-10-19 07:19:54.968516562 +0000 UTC] 	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:16 +0x22
[2018-10-19 07:19:54.968572705 +0000 UTC] main.dumpStackTrace()
[2018-10-19 07:19:54.968580292 +0000 UTC] 	src/github.com/fission/fission/environments/fetcher/cmd/main.go:24 +0x20
[2018-10-19 07:19:54.968587312 +0000 UTC] main.main.func1(0xc420038fc0)
[2018-10-19 07:19:54.968594021 +0000 UTC] 	src/github.com/fission/fission/environments/fetcher/cmd/main.go:35 +0x7d
[2018-10-19 07:19:54.968600917 +0000 UTC] created by main.main
[2018-10-19 07:19:54.968607412 +0000 UTC] 	src/github.com/fission/fission/environments/fetcher/cmd/main.go:32 +0xcb
[2018-10-20 15:00:35.282148937 +0000 UTC] 2018/10/20 15:00:35 fetcher received fetch request and started downloading: {1 {list-pkg-zip-pidd  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] }   9564e01b-d313-11e8-b06e-005056a3aefa [] []}
[2018-10-20 15:00:43.379317789 +0000 UTC] 2018/10/20 15:00:43 Successfully placed at /userfunc/9564e01b-d313-11e8-b06e-005056a3aefa
[2018-10-20 15:00:43.379415782 +0000 UTC] 2018/10/20 15:00:43 Checking secrets/cfgmaps
[2018-10-20 15:00:43.379426303 +0000 UTC] 2018/10/20 15:00:43 Completed fetch request
[2018-10-20 15:00:43.3800425 +0000 UTC] 2018/10/20 15:00:43 elapsed time in fetch request = 8.301390527s
[2018-10-20 15:12:24.082183965 +0000 UTC] 2018/10/20 15:12:24 Received SIGTERM : Dumping stack trace
[2018-10-20 15:12:24.181405566 +0000 UTC] goroutine 21 [running]:
[2018-10-20 15:12:24.181444733 +0000 UTC] runtime/debug.Stack(0x1a60b00, 0xc420056790, 0x5041ec)
[2018-10-20 15:12:24.181449816 +0000 UTC] 	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
[2018-10-20 15:12:24.181454266 +0000 UTC] runtime/debug.PrintStack()
[2018-10-20 15:12:24.181458029 +0000 UTC] 	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:16 +0x22
[2018-10-20 15:12:24.181493726 +0000 UTC] main.dumpStackTrace()
[2018-10-20 15:12:24.181498846 +0000 UTC] 	src/github.com/fission/fission/environments/fetcher/cmd/main.go:24 +0x20
[2018-10-20 15:12:24.181502696 +0000 UTC] main.main.func1(0xc4200ab860)
[2018-10-20 15:12:24.181506357 +0000 UTC] 	src/github.com/fission/fission/environments/fetcher/cmd/main.go:35 +0x7d
[2018-10-20 15:12:24.181510205 +0000 UTC] created by main.main
[2018-10-20 15:12:24.181513929 +0000 UTC] 	src/github.com/fission/fission/environments/fetcher/cmd/main.go:32 +0xcb
[2018-10-20 21:02:54.389514595 +0000 UTC] 2018/10/20 21:02:54 fetcher received fetch request and started downloading: {1 {list-pkg-zip-pidd  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] }   9564e01b-d313-11e8-b06e-005056a3aefa [] []}
[2018-10-20 21:02:58.780471487 +0000 UTC] 2018/10/20 21:02:58 Successfully placed at /userfunc/9564e01b-d313-11e8-b06e-005056a3aefa
[2018-10-20 21:02:58.881662092 +0000 UTC] 2018/10/20 21:02:58 Checking secrets/cfgmaps
[2018-10-20 21:02:58.890298367 +0000 UTC] 2018/10/20 21:02:58 Completed fetch request
[2018-10-20 21:02:58.890694962 +0000 UTC] 2018/10/20 21:02:58 elapsed time in fetch request = 4.639390966s
```

While it cannot read, Fission still can write to the list of entries:

```
~/dev/fonk/fonk-examples/guestbook/faas/fission/python master*
❯ fission function test --name create --body '{"text":"Hello from fission"}'
{
  "_id": "5bcb9942c830e0000166397a",
  "updatedAt": 1540069698664,
  "text": "Hello from fission"
}
```

And the other engines can read from it:

```
❯ kubeless function call list
{"entries":[{"_id":"5bcb9868377aa00005dade97","text":"Hello from openwhisk","updatedAt":1540069480195},{"_id":"5bcb9942c830e0000166397a","updatedAt":1540069698664,"text":"Hello from fission"}]}
```

To make sure that fission 'list' works fine, you can see it working correctly if fission is the only one writing to the database:

```
~/dev/fonk/fonk-examples/guestbook/faas/fission/python master* 7s
❯ fission function test --name list
{
  "entries": []
}
~/dev/fonk/fonk-examples/guestbook/faas/fission/python master*
❯ fission function test --name create --body '{"text":"Hello from fission"}'


{
  "text": "Hello from fission",
  "updatedAt": 1540069933691,
  "_id": "5bcb9a2d737e9d0001da8c9f"
}
~/dev/fonk/fonk-examples/guestbook/faas/fission/python master*
❯ fission function test --name list
{
  "entries": [
    {
      "updatedAt": 1540069933691,
      "_id": "5bcb9a2d737e9d0001da8c9f",
      "text": "Hello from fission"
    }
  ]
}
```

**Comment by petecj2** [comment]
This one was tricky.  Mongo stores data on a BSON format (Binary JSON) that includes typing.  Specifically in this case, an ObjectId is a BSON type so what gets stored raw is something like:

```
{
      "updatedAt": 1540069933691,
      "_id": ObjectId('5bcb9a2d737e9d0001da8c9f'),
      "text": "Hello from fission"
    }
```

The Node MongoDB library is sophisticated enough to parse this down into valid JSON, so when you parse it in Node, you get:

```
{
      "updatedAt": 1540069933691,
      "_id": "5bcb9a2d737e9d0001da8c9f",
      "text": "Hello from fission"
}
```

But for reasons that aren't entirely clear to me due to lack of general Python skills on my part, the Pymongo library does not parse this the same way so the `json.dumps()` call fails on it.  Prior to the commit I'm about to make, the `create` call manually set the `_id` field to avoid Mongo auto-setting it to include the BSON type, but I sort of fell into that with this Fission implementation without really understanding the implications of that manual set.

Soooo, the commit I'm about to make fixes the `create` so that it no longer manually sets the `_id` field, which will enable that field to be auto-set by Mongo and contain the typed BSON.  It then inelegantly sets the return JSON accordingly.  Similarly, the `list` call has been changed to inelegantly change the `_id` field so that the `json.dumps()` call won't fail any more.

I'll update the Guestbook/OpenFaaS/Python implementation as well, which I didn't try but looking at the code appears to suffer from the same issue since it's using the same Pymongo library. 

When the community grows to include someone who understands Pymongo better, I'm sure there will be a better solution to this, but for now brute force works.

**Comment by petecj2** [comment]
Needs fixing for OpenFaaS too

**Comment by juliogomez** [comment]
My hero.
